license="${mod_license}"
issueTrackerURL="https://github.com/RayTrace082/untamedwilds/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/RayTrace082/untamedwilds/"
logoFile="logo.png"
authors="RayTrace082"
description='''Expanding on the natural world of Minecraft.'''

[[mixins]]
config="untamedwilds.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

